kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarrclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      sonarrstorage: "yes"