kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: headphonesclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      app: headphones 