apiVersion: v1
kind: PersistentVolume
metadata:
  name: hedphones
  labels:
    app: headphones
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw/headphones
    server: nfs