[global]
  sendAnonymousUsage = false
  checkNewVersion = false

[api]
  dashboard = true
  insecure = true

[log]
  level = "WARN"

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"

[accessLog]

[providers]
  [providers.kubernetescrd]

  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
    watch = true

[entryPoints]
  [entryPoints.web]
    address = ":8000"
  [entryPoints.websecure]
    address = ":4443"

[certificatesResolvers.gandi.acme]

  # Email address used for registration.
  #
  # Required
  #
  email = "robby57@gmail.com"

  # File or key used for certificates storage.
  #
  # Required
  #
  storage = "/lets/acme.json"

  # CA server to use.
  # Uncomment the line to use Let's Encrypt's staging server,
  # leave commented to go to prod.
  #
  # Optional
  # Default: "https://acme-v02.api.letsencrypt.org/directory"
  #
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

  # KeyType to use.
  #
  # Optional
  # Default: "RSA4096"
  #
  # Available values : "EC256", "EC384", "RSA2048", "RSA4096", "RSA8192"
  #
  # keyType = "RSA4096"
    # Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
  # Note: mandatory for wildcard certificate generation.
  #
  # Optional
  #
  [certificatesResolvers.gandi.acme.dnsChallenge]

    # DNS provider used.
    #
    # Required
    #
    provider = "gandiv5"

    # By default, the provider will verify the TXT DNS challenge record before letting ACME verify.
    # If delayBeforeCheck is greater than zero, this check is delayed for the configured duration in seconds.
    # Useful if internal networks block external DNS queries.
    #
    # Optional
    # Default: 0
    #
    # delayBeforeCheck = 0

    # Use following DNS servers to resolve the FQDN authority.
    #
    # Optional
    # Default: empty
    #
    # resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

    # Disable the DNS propagation checks before notifying ACME that the DNS challenge is ready.
    #
    # NOT RECOMMENDED:
    # Increase the risk of reaching Let's Encrypt's rate limits.
    #
    # Optional
    # Default: false
    #
    # disablePropagationCheck = true
