apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver
  labels:
    app: plexserver
spec:
  capacity:
    storage: 1500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/plex
    server: nfs