kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plexserverclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1500Gi
  selector:
    matchLabels:
      app: plexserver