kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      nzbstorage: "yes"