apiVersion: v1
kind: PersistentVolume
metadata:
  name: ksabnzbddata
  labels:
    nzbstorage: "yes"
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw/sabnzbd
    server: nfs