apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnsbd-config
  labels:
    vol: sabnsbd-config
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw/sabnzbd
    server: nfs