apiVersion: v1
kind: PersistentVolume
metadata:
  name: ksabnzbd
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/ksabnzbd
    server: nfs