kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      vol: sabnsbd-config