kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      vol: sabnzbd-data