apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-data
  labels:
    vol: sabnzbd-data
spec:
  storageClassName: manual
  capacity:
    storage: 60Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/ksabnzbd
    server: nfs