apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: olibob/sabnzbd:2.3.9
        imagePullPolicy: Always
        name: sabnzbd
        volumeMounts:
          - mountPath: /dls
            name: data
          - mountPath: /datadir
            name: config
        ports:
          - containerPort: 8080
      initContainers:
      - name: install
        image: busybox
        command:
        - touch
        - "/work-dir/sabnzbd.ini"
        volumeMounts:
          - name: config
            mountPath: "/work-dir"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sabnzbd-data
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config