kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabdataclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      nzbstorage: "yes"