apiVersion: v1
kind: PersistentVolume
metadata:
  name: shaarli
  labels:
    app: shaarli
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw/shaarli
    server: nfs