apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr
  labels:
    vol: radarr
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw/radarr
    server: nfs