apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr
  labels:
    radarrstorage: "yes"
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw/radarr
    server: nfs