apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: busy-volume
    persistentVolumeClaim:
      claimName: srv-pvc
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - name: busy-volume
      mountPath: /mydata