---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default

data:
  users: |
    Ym9iOiRhcHIxJDRVM2JUN0thJFNFVXNjTTRGVy9uVmhiSTRWOUNVdy8Kb2xpOiRhcHIxJDlrbEduOERUJHZIZGlHaklYU2hKaWltdGhXNTVwbDE=
